image: "ruby:2.3.1"

before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - bundle exec rails db:migrate RAILS_ENV=test

rspec:
  script:
    - bundle exec rspec
  tags:
    - ruby
