image: "ruby:2.3.1"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - apt-get update -qq && apt-get install -yqq postgresql postgresql-contrib nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc) "${FLAGS[@]}" --path vendor

rails:
  script:
  - bundle exec rails db:migrate RAILS_ENV=test

rspec:
  script:
    - bundle exec spring rspec spec
  tags:
    - ruby
